### ISSUE TITLE
2023 Elected officers updated 

### ISSUE THREAD

**Issue by DerekDoug** [jdimichele/DanbyFireDept#20]
Update https://danbyfiredept.org/about 

202**4** Officers:
Line Officers	Staff Officers
Chief	John Gaden	President	Peter Goodman
1st Assistant Chief	Dan Saracino	Vice President	Derek Dougherty
2nd Assistant Chief	Peter Goodman	Secretary	Sharon Gaden
3rd Assistant Chief	Jethro Forbes	Treasurer	Steve Hilsdorf
Lieutenant	Simon Wyatt
At Large Director	**Ivan Ross**
At Large Director	Steve Hilsdorf

Change 2023 -> 2024
Change Amy Westmiller - > Ivan Ross

**Comment by jdimichele** [comment]
Changed Amy Westmiller to Ivan Ross. As for the date change, that will change to 2024 on Jan 1st of the New Year!
