### ISSUE TITLE
Research fillable forms and the best way to execute that for application submissions.

### ISSUE THREAD

**Issue by jdimichele** [jdimichele/DanbyFireDept#6]
Research the following:
 - Fillable Forms
 - Submission of Forms to web server/email
 - Integration for Paypal payments Moved to another issue

**Comment by DerekDoug** [comment]
https://forms.gle/d5xt31cJCpYfi1p97

**Comment by DerekDoug** [comment]
Fillable Forms - Application (Intrest) - Google Firebase | Address sign form - Google Form 
Submission of Forms to web server/email - Complete 
Integration for Paypal payments will be in a new issue
